"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cytrontts.py']
DATA_FILES = []
OPTIONS = {
  'iconfile': 'resources/icon.icns',
  'plist': {'CFBundleShortVersionString':'0.1.0'},
  'packages': [ 'requests' ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
